version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3080:80
    env_file:  
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      PMA_PORT: ${DATABASE_PORT}

  spendo-back:
    build: 
      context: .
      args:
        - API_PORT:${API_PORT}
    env_file:
      - .env
    depends_on: 
      mysql:
        condition: service_healthy
        restart: true
    ports: 
      - ${API_PORT}:${API_PORT}